---
title: "Technical Documentation"
output: html_document
---

## Zone Definitions

Zone	| Rollout Month Due Date | Zip Codes	
:---- | :----------- | :------
1	| March 2021 | 44120, 44135	
2	| June 2021 | 44106, 44111
3	| September 2021 | 44102, 44142
4	| December 2021 | 44107, 44110, 44113, 44130
5	| March 2022 | 44103, 44119, 44128, 44129, 44144
6	| June 2022 | 44104, 44108, 44114, 44117, 44131, 44134
7	| September 2022 | 44109, 44115, 44127, 44137
8	| December 2022 | 44105, 44112, 44118, 44121, 44122, 44125

<br>

## Lead Poisoning

**Percent of Children Tested:**

All lead tests (both those done through a capillary puncture or venous lab draw) that are reported to the Ohio Department of Health (ODH) for children aged 0 to 6 residing in Cuyahoga County are provided to the Center on Poverty and Community Development on an ongoing basis. The address of the child at the time of the test is included in the data from ODH.

Venous tests are the only tests considered to be confirmatory by ODH.  This dashboard only counts confirmed tests. If a child receives more than one test in a year, they are counted only once.

Annual Census data from the American Communities Survey is used to calculate the number of children aged 0-3 and 0-6 at each geography available in the dashboard. 

The percent of children tested in each year is calculated by summing the number of children (0-3 and 0-6) with a confirmed test in each geography and dividing by the Census estimate of children (0-3 and 0-6) in that geography.


**Percent of Children with an Elevated Blood Lead Level (EBLL) of those tested**

An Elevated Blood Lead Level (EBLL) is defined according to the current standard of >= 5 micrograms per deciliter.  The standard used to be higher and may continue to trend downward. The data practice at the Center on Poverty and Community Development is to retroactively flag previous testing data to modern standards. 

The number of children aged 0-3 and 0-6 with a confirmed EBLL in each year are summed by geography.  This number is divided by the total number of children aged 0-3 and 0-6 tested each year.  If a child receives more than one test screening or more than one EBLL in a year, they are counted only once.

**Data Suppression**

*General Suppression Rules:*

**1)** The ACS population estimates are based on 5 year averages and become less reliable in smaller populations. For this reason, data is suppressed if the estimated number of children of a racial group (i.e. Black, white, Hispanic, other) is less than 50 in the geographic area (i.e. zip code, neighborhood, rollout zone). 

**2)** Children were not included in the lead-related indicators if the address listed on their lead testing was the street address of DCFS headquarters because we cannot confirm that they reside in that geography. 


*Confidentiality:*

In order to avoid the possible disclosure of any confidential information of lead tested children, we are required by the Ohio Department of Health (ODH) to suppress data if the counts or rates do not meet certain thresholds. Lead-related indicators are suppressed in the following circumstances: 
 
**1)** There are less than 10 children that were tested for lead in any geographic area or in any racial group. 
 
**2)** The difference between the numerator and denominator of the indicator is less than 10. For example, if there are 30 white children tested for lead in a geographic area and 25 of them have an EBLL, the number and percent for both tested and EBLL must be suppressed. If there are 200 Black children living in a geographic area and 192 of them get lead tested, the number and percent for both tested and EBLL must be suppressed.

For more information on ODH guidelines: https://odh.ohio.gov/wps/portal/gov/odh/explore-data-and-stats/resources/Disclosure-Limitation-Standard


*The lead data used in this dashboard come from the Ohio Department of Health. This should not be considered an endorsement of this study or these conclusions by the Ohio Department of Health.*

<br>

## Housing Market

**Rental Registrations**
 
Rental registration records are provided to the Center on Poverty and Community Development from the City of Cleveland Department of Building and Housing.  Data are cleaned and standardized so that address and parcel numbers are consistent. Records without parcel numbers are geocoded to a building location and spatially matched to a parcel.

Records are then coded to their Lead Safe Certification roll-out zone (1 through 8), neighborhood, and zip code. Records that can not be coded to a geography are coded as “unknown geography” and are not included in the dashboard numbers. Records are categorized as follows: records with a status of “renewed” or “registration renewed” are coded as “active” during the quarter first considered active and through the end of the calendar year unless the status is changed to  “closed” or “no renewal.” 

Records are then deduplicated by parcel. When multiple records are associated with a given parcel, we prioritize keeping the record with an active status. This creates the most consistent depiction of a property’s rental registration status over time.

Annual/quarterly counts of rental registration records by record status and geographies of interest are then created. Indicators are coded based on the last status in the given quarter. Yearly indicators prioritize the active status, counting a property as active if it is active for any portion of the year. Counts of units reflect the unit count indicated in the rental registration record. In instances where rental registration records are deduplicated and unit count is inconsistent across records, the highest unit count associated with a record is used.

**Evictions**

Cleveland Municipal Court eviction cases counts are scraped weekly from the online court docket system and compiled.  These data contain filing records and attributes associated with the filing, docket entry records, and event records. The addresses subject to the eviction filing are geocoded and assigned to geographies of interest. Filing records, docket entries, and event records are linked together. We search docket entries and event records for move-outs scheduled to create a flat file of eviction filings and move-outs scheduled. A move-out can be scheduled when a judgment is found for the plaintiff in the eviction case, and the plaintiff purchases a writ of restitution and schedules a move-out with the court. Counts of filings and move-outs scheduled are compiled by geographies of interest.

Because properties owned by Cleveland Municipal Housing Authority (CMHA) are not subject to rental registration nor the lead safe ordinance, eviction cases in which CMHA is the plaintiff have been excluded from the counts listed in the dashboard.

* Special thanks to [Sam Learner](https://www.samlearner.com/) for generously offering his time and technical expertise to the Poverty Center by building and maintaining the tool for scraping records from the court docket system. 

<br>

## Lead Safe Certification

Lead Safe Certification records are provided to the Center on Poverty and Community Development from the City of Cleveland Department of Building and Housing.  Data are cleaned and standardized so that address and parcel numbers are consistent. Records without parcel numbers are geocoded to a building location and spatially matched to a parcel when possible.

Records are then coded to their Lead Safe Certification roll-out zone (1 through 8), neighborhood, and zip code. Records that can not be linked to a geography are coded as “unknown geography” and are not included in the dashboard numbers. 

The owner of a rental property submits an application to the Department of Building and Housing to get a lead safe certification . The records provided to the Center on Poverty and Community Development organize submitted applications into four categories to reflect the current status of the application: Pass, Fail, Pending, and Exempt. 

Exempt properties include those for which an application for lead safe certification was submitted to the Department of Building and Housing, but a review of the property determined it was not subject to the requirements of the lead safe legislation. Typically, these are rental properties that were built after 1978 or that are owner-occupied.

For a detailed explanation of the certification process: https://www.clevelandohio.gov/CityofCleveland/Home/Government/CityAgencies/BuildingHousing/LeadCertification

<br>

## Loans and Grants

The loans and grants data is provided by CHN Housing Partners on a quarterly basis.

**Application/Project Status**

`Application inactive` includes applications that are referred elsewhere, that choose to withdraw for any reason, or that are determined to be ineligible. 
`Application opened` includes applications that are pending submission.
`Application in review` includes applications that have been submitted and are under review with CHN or are on a wait list until additional materials are provided. 
`Project Active` includes applications that have been accepted for funding and are now in the construction management pipeline. 
`Project complete` includes projects that have achieved lead clearance.

**Funding Suppression**

Following CHN guidelines, funding total and average are suppressed if there are 3 or fewer units with an estimated funding award in a particular geography.


<br>


## Resource Center

The Resource Center data is provided by Environmental Health Watch (EHW) on a quarterly basis. Additional community engagement and workforce metrics coming soon. 

**Callers**

The contact type and interest area of new callers are displayed in the dashboard.

`Contact Type` - `"Tenant"` is an individual who is renting their house or apartment.
`"Landlord"` is an individual who owns a house or apartment and rents it to someone else. 
`"Home Owner"` is an individual who owns a house or apartment and lives in it themselves. 
`"Anonymous Contact"` is an individual who chose not to share their contact type with the Resource Center.

`Contact Interest Area` - Category definitions are coming soon. Interest area is listed as '"Missing/Training Sign-Up"' if it was not captured by the intake staff or if an individual signed up for a lead remediation training via the Event Brite platform. EHW is working to better differentiate these two categories in future quarters. 

**Training**

`Lead Safe Landlord Certification Process Informational Q/A` This training presents information on the Lead Safe law and certification requirements. Attendees will learn about the 6-Step process for achieving certification from the City of Cleveland Building & Housing. The training will also review the Zip Code Rollout process, options for a landlord or property manager to complete their own work, referrals for loans and grants, and how a landlord might qualify for incentives to receive money back on work completed to achieve the Lead Safe Certification.

`Lead 101` This training presents information on the Lead Safe Cleveland Coalition, the resources and teams available to support landlords/homeowners, along with information on the who, what, when, where, and why for all things lead poisoning and prevention.

`Renovation, Repair & Painting (RRP) Certification` This U.S. Environmental Protection Agency (EPA) certified training will equip individuals with skill and knowledge to join the lead remediation workforce. Landlords/property managers who want to complete work on their own properties are required by federal law to have this certification. 

`Clearance Technician Certification` This training will equip individuals with the skills necessary to complete a Lead Clearance, which is the examination that determines a property to be lead safe.

`Hands-On Vetting Experience` This training offers an opportunity to receive hands-on engagement and experience for either completing lead safe remediation work and/or completing lead clearance examinations on properties in Cleveland. The completion of this training provides an opportunity to be added to the vetted list of contracted workers that will be publicized for the city of Cleveland community.

The name for the experiential portion of the workforce training changed from "LSRC: Free Two-Part Training" to "Free Hands-On Vetting Experience".

