---
title: "Panel de datos de la Coalición para Eliminar la Intoxicación por Plomo en Cleveland"
navbar:
  left:
  - text: "Home"
    href: index.html
  - text: "Download some data"
    href: data-download.html
  right:
  - text: "In English"
    href: index.html
 
output_dir: "."
output: 
  html_document: 
    css: styles_index.css
    include: 
      after_body: footer_espanol.html
editor_options: 
  markdown: 
    wrap: 72
---



Ningún niño debería estar expuesto al envenenamiento con plomo. Según los Centros para el Control y la Prevención de Enfermedades, "la exposición al plomo puede dañar gravemente la salud de un niño, incluidos daños al cerebro y el sistema nervioso, crecimiento y desarrollo lento, problemas de aprendizaje y comportamiento y problemas de audición y habla."^[[fuente: Centro Nacional de Salud Ambiental](https://www.cdc.gov/nceh/features/leadpoisoning/index.html#:~:text=Exposure%20to%20lead%20can%20seriously,in%20children%20has%20been%20identified.)]

<br>

 
La [Coalición](https://leadsafecle.org) para Eliminar la Intoxicación por Plomo en Cleveland  está trabajando para que todas las  viviendas de nuestra ciudad sean seguras, sin riesgo de intoxicar a sus residentes con plomo.

<br>

 
La mayoría de las casas construidas antes de 1978 usaban pintura con plomo, lo cual representa un peligro para los niños. La [ciudad de Cleveland](https://cityofcleveland.legistar.com/LegislationDetail.aspx?ID=3971384&GUID=55AA3B1D-224B-41FD-B228-FC528D10269C&Options=ID%7CText%7C&Search=lead) ahora requiere que todas las propiedades de alquiler construidas antes de 1978 tengan una certificación de seguridad contra el plomo. El certificado garantiza que la casa ha sido inspeccionada por un profesional autorizado y [no tiene ningún peligro actual de plomo](https://leadsafecle.org/6steps). Todas las viviendas de alquiler deberán obtener una certificación según el [calendario dispuesto](https://leadsafecle.org/zip-code-groupings). Los plazos para cumplir con la certificación están dados por código postal y empiezan a cumplirse partir de Marzo de 2021.

<br>
 
El [Panel de Datos de la La Coalición](https://cwru-urb-pov.shinyapps.io/lead_flexdashboard_blank_3_30_2021/) para Eliminar la Intoxicación por Plomo en Cleveland  ofrece respuestas a preguntas comunes e información sobre la implementación de esta nueva ley y cómo está afectando a los niños, las familias y los vecindarios.

<br>
 
Estas son solo algunas de las preguntas que el tablero puede ayudar a responder:


<br>

<div class="card" style="width: 50 rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item" id="q1"><a href="https://cwru-urb-pov.shinyapps.io/lead_flexdashboard_blank_3_30_2021/#section-baseline">¿Cómo ha cambiado la cantidad de niños envenenados por plomo a lo largo del tiempo en los vecindarios de Cleveland? </a></li>
     <li class="list-group-item" id="q2"><a href="https://cwru-urb-pov.shinyapps.io/lead_flexdashboard_blank_3_30_2021/#section-implementation-and-monitoring">¿Cómo varían las tasas de detección y prueba de plomo en la ciudad a lo largo del tiempo?</a></li>
     </ul>
</div>

<br>


<div class="card" style="width: 50 rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item" id="q3"><a href="https://cwru-urb-pov.shinyapps.io/lead_flexdashboard_blank_3_30_2021/#section-baseline">¿Cuántos desalojos y órdenes de mudanza se han producido en mi vecindario?</a></li>
     <li class="list-group-item" id="q4"><a href="https://cwru-urb-pov.shinyapps.io/lead_flexdashboard_blank_3_30_2021/#section-implementation-and-monitoring">¿Cuántas propiedades de alquiler han sido certificadas como seguras para el plomo?</a></li>
     </ul>
</div>

<br>

<div class="card" style="width: 50 rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item" id="q5"><a href="https://cwru-urb-pov.shinyapps.io/lead_flexdashboard_blank_3_30_2021/#section-baseline">¿Cuántos propietarios han recibido préstamos o subvenciones para que su propiedad sea segura con el plomo?</a></li>
     <li class="list-group-item" id="q6"><a href="https://cwru-urb-pov.shinyapps.io/lead_flexdashboard_blank_3_30_2021/#section-implementation-and-monitoring">¿Cuántos profesionales han sido capacitados y certificados para detectar plomo en los hogares?</a></li>
     </ul>
</div>

<br>


<div class="card" style="width: 50 rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item" id="q7"><a href="https://cwru-urb-pov.shinyapps.io/lead_flexdashboard_blank_3_30_2021/#section-development-advocacy">¿Cuánto dinero ha recaudado la Coalición para Eliminar la Intoxicación por Plomo en Cleveland?</a></li>
</div>


<br>

Para obtener más información sobre el esfuerzo actual para hacer que las casas de Cleveland sean seguras con el plomo, ayuda y recursos locales, y más, visite la [Coalición de Cleveland con Plomo](https://leadsafecle.org).

