---
title: "Lead Safe Cleveland Coalition Data Dashboard"
output: 
  html_document: 
    css: styles_index.css
    include: 
      after_body: footer.html
editor_options: 
  markdown: 
    wrap: 72
---



No child should ever be lead poisoned. According to the Centers for Disease Control and Prevention, "exposure to lead can seriously harm a child’s health, including damage to the brain and nervous system, slowed growth and development, learning and behavior problems, and hearing and speech problems."^[[source: National Center for Environmental Health](https://www.cdc.gov/nceh/features/leadpoisoning/index.html#:~:text=Exposure%20to%20lead%20can%20seriously,in%20children%20has%20been%20identified.)]

<br>

The [Lead Safe Cleveland Coalition](https://leadsafecle.org) is working to make housing lead safe for everyone in Cleveland. 

<br>

Most homes built before 1978 used lead paint, which poses a danger for children. The [City of Cleveland](https://cityofcleveland.legistar.com/LegislationDetail.aspx?ID=3971384&GUID=55AA3B1D-224B-41FD-B228-FC528D10269C&Options=ID%7CText%7C&Search=lead) now requires that all rental properties built before 1978 have a Lead Safe Certification. That means the home has been inspected by a certified professional and [does not have any current lead hazards](https://leadsafecle.org/6steps). All rentals will have to get a certification starting in March 2021, [a few ZIP codes at a time](https://leadsafecle.org/zip-code-groupings).

<br>

The [Lead Safe Cleveland Coalition Data Dashboard](https://cwru-urb-pov.shinyapps.io/lscc_data_dashboard_beta/) has answers to common questions and information on the rollout of this new law and how it is affecting children, families and neighborhoods. 

<br>

Here are just a few of the questions the dashboard can help answer:

<br>


<div class="card" style="width: 50 rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item" id="q1"><a href="https://cwru-urb-pov.shinyapps.io/lscc_data_dashboard_beta/#section-baseline" target="_blank">How has the number of children poisoned by lead changed over time?</a></li>
     <li class="list-group-item" id="q2"><a href="https://cwru-urb-pov.shinyapps.io/lscc_data_dashboard_beta/#section-baseline" target="_blank">How do lead screening and testing rates vary across the city?</a></li>
     </ul>
</div>

<br>


<div class="card" style="width: 50 rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item" id="q3"><a href="https://cwru-urb-pov.shinyapps.io/lscc_data_dashboard_beta/#section-baseline-1" target="_blank">How many evictions and move-out orders have occurred in my neighborhood? </a></li>
     <li class="list-group-item" id="q4"><a href="https://cwru-urb-pov.shinyapps.io/lscc_data_dashboard_beta/#section-implementation-and-monitoring-1" target="_blank">How many rental properties have been certified as Lead Safe? (Coming September 2021)</a></li>
     </ul>
</div>

<br>

<div class="card" style="width: 50 rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item" id="q5"><a href="https://cwru-urb-pov.shinyapps.io/lscc_data_dashboard_beta/#section-resource-center" target="_blank">How many lead safe technicians have been trained and certified? (Coming September 2021)</a></li>
     <li class="list-group-item" id="q6"><a href="https://cwru-urb-pov.shinyapps.io/lscc_data_dashboard_beta/#section-loans-grants" target="_blank">How many property owners have received loans or grants to make their property lead safe? (Coming September 2021)</a></li>
     </ul>
</div>

<br>


<div class="card" style="width: 50 rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item" id="q7"><a href="https://cwru-urb-pov.shinyapps.io/lscc_data_dashboard_beta/#section-development-advocacy" target="_blank">How much money has the Lead Safe Cleveland Coalition raised? (Coming September 2021)</a></li>
</div>

<br>

For more information about the current effort to make Cleveland's homes lead safe, local help and resources, and more, please visit the [Lead Safe Cleveland Coalition](https://leadsafecle.org).




